name: Create the clevercloud app for the production environment

on: workflow_dispatch
jobs:
  create:
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    steps:
      - name: Create a frontend application frontend for the production environment, with portail-usager-carto-production alias, based in Paris.
        run: clever create --type static-apache portail-usager-carto-production --alias portail-usager-carto-production --region par --org ${{ secrets.CLEVER_ORG_ID }}
      - name: Scale down to nano
        run: clever scale --flavor nano
