name: Test for schedule

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trying to enulerate all branches
        run: git for-each-ref refs/heads/feature/*

